// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using com.lifepixer.mangapixer.Server.Persistence;

#nullable disable

namespace com.lifepixer.mangapixer.Server.Persistence.Migrations
{
    [DbContext(typeof(MangaPixerDbContext))]
    [Migration("20260909133505_AddContinueReadingHidden")]
    partial class AddContinueReadingHidden
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("com.lifepixer.mangapixer.Server.Persistence.Entities.ArchiveItemEntity", b =>
                {
                    b.Property<long>("NodeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AnalysisError")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int>("AnalysisState")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArchiveFormat")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ByteLength")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ContentVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileIdentity")
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastAnalyzedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ModificationTicks")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PageCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StrongHash")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long?>("StrongHashSourceVersion")
                        .HasColumnType("INTEGER");

                    b.HasKey("NodeId");

                    b.HasIndex("AnalysisState");

                    b.HasIndex("ContentVersion");

                    b.ToTable("archive_items", (string)null);
                });

            modelBuilder.Entity("com.lifepixer.mangapixer.Server.Persistence.Entities.AuditEventEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long?>("ActorUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<long?>("TargetItemId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TargetLibraryId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TargetUserId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Timestamp")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("Timestamp");

                    b.ToTable("audit_events", (string)null);
                });

            modelBuilder.Entity("com.lifepixer.mangapixer.Server.Persistence.Entities.BookmarkEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("ContentVersion")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EntryKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<double>("NormalizedAnchor")
                        .HasColumnType("REAL");

                    b.Property<int>("Ordinal")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ItemId");

                    b.ToTable("bookmarks", (string)null);
                });

            modelBuilder.Entity("com.lifepixer.mangapixer.Server.Persistence.Entities.CacheEntryEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("ByteSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CacheFilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CacheKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("CacheVersion")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastAccessedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CacheKey")
                        .IsUnique();

                    b.HasIndex("State", "LastAccessedAt");

                    b.ToTable("cache_entries", (string)null);
                });

            modelBuilder.Entity("com.lifepixer.mangapixer.Server.Persistence.Entities.CatalogNodeEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Availability")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastSeenScanRevision")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LibraryId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ParentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PathKey")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SortKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LibraryId");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("LibraryId", "PathKey")
                        .IsUnique();

                    b.HasIndex("ParentId", "Kind", "SortKey");

                    b.ToTable("catalog_nodes", (string)null);
                });

            modelBuilder.Entity("com.lifepixer.mangapixer.Server.Persistence.Entities.FolderReaderDefaultEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("NodeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReaderMode")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NodeId")
                        .IsUnique();

                    b.ToTable("folder_reader_defaults", (string)null);
                });

            modelBuilder.Entity("com.lifepixer.mangapixer.Server.Persistence.Entities.ItemReaderOverridesEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Background")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CoverOffset")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Direction")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FitMode")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ReaderMode")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SpreadOffset")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ItemId")
                        .IsUnique();

                    b.ToTable("item_reader_overrides", (string)null);
                });

            modelBuilder.Entity("com.lifepixer.mangapixer.Server.Persistence.Entities.JobEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Attempt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CompletedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long?>("LeaseExpiry")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LeaseOwner")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long?>("LibraryId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProgressCurrent")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProgressTotal")
                        .HasColumnType("INTEGER");

                    b.Property<long>("QueuedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SanitizedError")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<long?>("StartedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LibraryId");

                    b.HasIndex("Status", "LeaseExpiry");

                    b.ToTable("jobs", (string)null);
                });

            modelBuilder.Entity("com.lifepixer.mangapixer.Server.Persistence.Entities.LibraryEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CaseComparisonPolicy")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<long>("CatalogRevision")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DefaultReaderMode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastScanCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("RootIdentity")
                        .HasColumnType("TEXT");

                    b.Property<string>("RootPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ScanSchedule")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.ToTable("libraries", (string)null);
                });

            modelBuilder.Entity("com.lifepixer.mangapixer.Server.Persistence.Entities.LibraryGrantEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("GrantedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LibraryId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LibraryId");

                    b.HasIndex("UserId", "LibraryId")
                        .IsUnique();

                    b.ToTable("library_grants", (string)null);
                });

            modelBuilder.Entity("com.lifepixer.mangapixer.Server.Persistence.Entities.PageEntryEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnimationState")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ByteSize")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ContentVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EntryKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("Ordinal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PageState")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceEntryLocator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("ItemId", "ContentVersion", "EntryKey")
                        .IsUnique();

                    b.HasIndex("ItemId", "ContentVersion", "Ordinal")
                        .IsUnique();

                    b.ToTable("page_entries", (string)null);
                });

            modelBuilder.Entity("com.lifepixer.mangapixer.Server.Persistence.Entities.ReadMarkEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MarkedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("UserId", "ItemId")
                        .IsUnique();

                    b.ToTable("read_marks", (string)null);
                });

            modelBuilder.Entity("com.lifepixer.mangapixer.Server.Persistence.Entities.ReaderPreferencesEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DefaultReaderMode")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PreferDoubleSpread")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PreferredBackground")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ReducedMotion")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("reader_preferences", (string)null);
                });

            modelBuilder.Entity("com.lifepixer.mangapixer.Server.Persistence.Entities.ReadingProgressEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CompletedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ContentVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EntryKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("HiddenFromContinue")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastMutationId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("NormalizedAnchor")
                        .HasColumnType("REAL");

                    b.Property<int>("Ordinal")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Revision")
                        .HasColumnType("INTEGER");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ItemId")
                        .IsUnique();

                    b.HasIndex("UserId", "UpdatedAt");

                    b.ToTable("reading_progress", (string)null);
                });

            modelBuilder.Entity("com.lifepixer.mangapixer.Server.Persistence.Entities.ScanObservationEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("ByteLength")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("FileIdentity")
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LibraryId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ModificationTicks")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ObservationStatus")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ParentNodeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ParentPathKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PathKey")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SanitizedError")
                        .HasColumnType("TEXT");

                    b.Property<long>("ScanRunId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ScanRunId");

                    b.HasIndex("LibraryId", "PathKey");

                    b.ToTable("scan_observations", (string)null);
                });

            modelBuilder.Entity("com.lifepixer.mangapixer.Server.Persistence.Entities.ScanRunEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CompletedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LeaseExpiry")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LeaseOwner")
                        .HasColumnType("TEXT");

                    b.Property<long>("LibraryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NodesAdded")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NodesObserved")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NodesTombstoned")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NodesUpdated")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SanitizedError")
                        .HasColumnType("TEXT");

                    b.Property<long>("ScanRevision")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StartedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LibraryId");

                    b.HasIndex("Status");

                    b.ToTable("scan_runs", (string)null);
                });

            modelBuilder.Entity("com.lifepixer.mangapixer.Server.Persistence.Entities.SessionEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("ExpiresAt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("INTEGER");

                    b.Property<long>("IssuedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("TicketId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("TicketId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("sessions", (string)null);
                });

            modelBuilder.Entity("com.lifepixer.mangapixer.Server.Persistence.Entities.UserEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ForcePasswordChange")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastLoginAt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LockoutEnd")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NormalizedUserName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique();

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("com.lifepixer.mangapixer.Server.Persistence.Entities.ArchiveItemEntity", b =>
                {
                    b.HasOne("com.lifepixer.mangapixer.Server.Persistence.Entities.CatalogNodeEntity", "Node")
                        .WithOne("ArchiveItem")
                        .HasForeignKey("com.lifepixer.mangapixer.Server.Persistence.Entities.ArchiveItemEntity", "NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Node");
                });

            modelBuilder.Entity("com.lifepixer.mangapixer.Server.Persistence.Entities.BookmarkEntity", b =>
                {
                    b.HasOne("com.lifepixer.mangapixer.Server.Persistence.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("com.lifepixer.mangapixer.Server.Persistence.Entities.CatalogNodeEntity", b =>
                {
                    b.HasOne("com.lifepixer.mangapixer.Server.Persistence.Entities.LibraryEntity", "Library")
                        .WithMany("Nodes")
                        .HasForeignKey("LibraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("com.lifepixer.mangapixer.Server.Persistence.Entities.CatalogNodeEntity", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Library");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("com.lifepixer.mangapixer.Server.Persistence.Entities.FolderReaderDefaultEntity", b =>
                {
                    b.HasOne("com.lifepixer.mangapixer.Server.Persistence.Entities.CatalogNodeEntity", "Node")
                        .WithMany()
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Node");
                });

            modelBuilder.Entity("com.lifepixer.mangapixer.Server.Persistence.Entities.ItemReaderOverridesEntity", b =>
                {
                    b.HasOne("com.lifepixer.mangapixer.Server.Persistence.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("com.lifepixer.mangapixer.Server.Persistence.Entities.LibraryGrantEntity", b =>
                {
                    b.HasOne("com.lifepixer.mangapixer.Server.Persistence.Entities.LibraryEntity", "Library")
                        .WithMany("Grants")
                        .HasForeignKey("LibraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("com.lifepixer.mangapixer.Server.Persistence.Entities.UserEntity", "User")
                        .WithMany("LibraryGrants")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Library");

                    b.Navigation("User");
                });

            modelBuilder.Entity("com.lifepixer.mangapixer.Server.Persistence.Entities.PageEntryEntity", b =>
                {
                    b.HasOne("com.lifepixer.mangapixer.Server.Persistence.Entities.ArchiveItemEntity", "Item")
                        .WithMany("Pages")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("com.lifepixer.mangapixer.Server.Persistence.Entities.ReadMarkEntity", b =>
                {
                    b.HasOne("com.lifepixer.mangapixer.Server.Persistence.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("com.lifepixer.mangapixer.Server.Persistence.Entities.ReaderPreferencesEntity", b =>
                {
                    b.HasOne("com.lifepixer.mangapixer.Server.Persistence.Entities.UserEntity", "User")
                        .WithOne("Preferences")
                        .HasForeignKey("com.lifepixer.mangapixer.Server.Persistence.Entities.ReaderPreferencesEntity", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("com.lifepixer.mangapixer.Server.Persistence.Entities.ReadingProgressEntity", b =>
                {
                    b.HasOne("com.lifepixer.mangapixer.Server.Persistence.Entities.UserEntity", "User")
                        .WithMany("ReadingProgress")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("com.lifepixer.mangapixer.Server.Persistence.Entities.SessionEntity", b =>
                {
                    b.HasOne("com.lifepixer.mangapixer.Server.Persistence.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("com.lifepixer.mangapixer.Server.Persistence.Entities.ArchiveItemEntity", b =>
                {
                    b.Navigation("Pages");
                });

            modelBuilder.Entity("com.lifepixer.mangapixer.Server.Persistence.Entities.CatalogNodeEntity", b =>
                {
                    b.Navigation("ArchiveItem");
                });

            modelBuilder.Entity("com.lifepixer.mangapixer.Server.Persistence.Entities.LibraryEntity", b =>
                {
                    b.Navigation("Grants");

                    b.Navigation("Nodes");
                });

            modelBuilder.Entity("com.lifepixer.mangapixer.Server.Persistence.Entities.UserEntity", b =>
                {
                    b.Navigation("LibraryGrants");

                    b.Navigation("Preferences");

                    b.Navigation("ReadingProgress");
                });
#pragma warning restore 612, 618
        }
    }
}
