// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using com.lifepixer.mangapixer.Server.Persistence;

#nullable disable

namespace com.lifepixer.mangapixer.Server.Persistence.Migrations
{
    [DbContext(typeof(MangaPixerDbContext))]
    partial class MangaPixerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("com.lifepixer.mangapixer.Server.Persistence.Entities.AppSettingsEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("BackupIntervalHours")
                        .HasColumnType("REAL");

                    b.Property<string>("BackupLocation")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("BackupLocationMarkerId")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int?>("BackupRetentionCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("BackupsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MetadataBackoffStep")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("MetadataBackoffUntil")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("MetadataBudgetDayUtc")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MetadataBudgetUsed")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("MetadataConsentAt")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MetadataConsentVersion")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MetadataDailyBudget")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("MetadataEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("MetadataLastErrorAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MetadataLastErrorCode")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<bool>("MetadataSeriesInfoHidden")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UpdateCheckEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("UpdateLastCheckedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpdateLastKnownLatestVersion")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("app_settings", (string)null);
                });

            modelBuilder.Entity("com.lifepixer.mangapixer.Server.Persistence.Entities.ArchiveItemEntity", b =>
                {
                    b.Property<long>("NodeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AnalysisError")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int>("AnalysisState")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArchiveFormat")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ByteLength")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentSignature")
                        .HasMaxLength(96)
                        .HasColumnType("TEXT");

                    b.Property<long>("ContentVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileIdentity")
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastAnalyzedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ModificationTicks")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PageCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StrongHash")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long?>("StrongHashSourceVersion")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ThumbnailContentVersion")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ThumbnailState")
                        .HasColumnType("INTEGER");

                    b.HasKey("NodeId");

                    b.HasIndex("AnalysisState");

                    b.HasIndex("ContentVersion");

                    b.HasIndex("ThumbnailState");

                    b.ToTable("archive_items", (string)null);
                });

            modelBuilder.Entity("com.lifepixer.mangapixer.Server.Persistence.Entities.ArchiveSpreadLayoutEntity", b =>
                {
                    b.Property<long>("NodeId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ContentVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SpreadStartsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("NodeId");

                    b.ToTable("archive_spread_layouts", (string)null);
                });

            modelBuilder.Entity("com.lifepixer.mangapixer.Server.Persistence.Entities.AuditEventEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long?>("ActorUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<long?>("TargetItemId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TargetLibraryId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TargetUserId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Timestamp")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("Timestamp");

                    b.ToTable("audit_events", (string)null);
                });

            modelBuilder.Entity("com.lifepixer.mangapixer.Server.Persistence.Entities.BookmarkEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("ContentVersion")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EntryKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<double>("NormalizedAnchor")
                        .HasColumnType("REAL");

                    b.Property<int>("Ordinal")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ItemId");

                    b.ToTable("bookmarks", (string)null);
                });

            modelBuilder.Entity("com.lifepixer.mangapixer.Server.Persistence.Entities.CacheEntryEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("ByteSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CacheFilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CacheKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("CacheVersion")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastAccessedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CacheKey")
                        .IsUnique();

                    b.HasIndex("State", "LastAccessedAt");

                    b.ToTable("cache_entries", (string)null);
                });

            modelBuilder.Entity("com.lifepixer.mangapixer.Server.Persistence.Entities.CatalogNodeEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Availability")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastSeenScanRevision")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LatestDescendantAddedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LibraryId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ParentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PathKey")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SortKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LibraryId");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("LibraryId", "PathKey")
                        .IsUnique();

                    b.HasIndex("ParentId", "Kind", "SortKey");

                    b.ToTable("catalog_nodes", (string)null);
                });

            modelBuilder.Entity("com.lifepixer.mangapixer.Server.Persistence.Entities.EmbeddedMetadataEntity", b =>
                {
                    b.Property<long>("NodeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AgeRating")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("AlternateSeries")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<long>("ContentVersion")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Count")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatorsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Format")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("GenresJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gtin")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Imprint")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("LanguageIso")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int?>("MangaDirection")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Month")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("Number")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Publisher")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<long>("ReadAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Schema")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Series")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("SeriesGroup")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StoryArc")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT");

                    b.Property<string>("TagsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Volume")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WebUrlsJson")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("NodeId");

                    b.HasIndex("State");

                    b.ToTable("embedded_metadata", (string)null);
                });

            modelBuilder.Entity("com.lifepixer.mangapixer.Server.Persistence.Entities.FavoriteEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CatalogNodeId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CatalogNodeId");

                    b.HasIndex("UserId", "CatalogNodeId")
                        .IsUnique();

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("favorites", (string)null);
                });

            modelBuilder.Entity("com.lifepixer.mangapixer.Server.Persistence.Entities.FolderMetadataPrecedenceEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("NodeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Precedence")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NodeId")
                        .IsUnique();

                    b.ToTable("folder_metadata_precedence", (string)null);
                });

            modelBuilder.Entity("com.lifepixer.mangapixer.Server.Persistence.Entities.FolderReaderDefaultEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("NodeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReaderMode")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NodeId")
                        .IsUnique();

                    b.ToTable("folder_reader_defaults", (string)null);
                });

            modelBuilder.Entity("com.lifepixer.mangapixer.Server.Persistence.Entities.HomeExcludedLibraryEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("LibraryId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MarkedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "LibraryId")
                        .IsUnique();

                    b.ToTable("home_excluded_libraries", (string)null);
                });

            modelBuilder.Entity("com.lifepixer.mangapixer.Server.Persistence.Entities.ItemReaderOverridesEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Background")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CoverOffset")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Direction")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FitMode")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ReaderMode")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SpreadOffset")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ItemId")
                        .IsUnique();

                    b.ToTable("item_reader_overrides", (string)null);
                });

            modelBuilder.Entity("com.lifepixer.mangapixer.Server.Persistence.Entities.JobEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Attempt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CompletedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long?>("LeaseExpiry")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LeaseOwner")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long?>("LibraryId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProgressCurrent")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProgressTotal")
                        .HasColumnType("INTEGER");

                    b.Property<long>("QueuedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SanitizedError")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<long?>("StartedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LibraryId");

                    b.HasIndex("Status", "LeaseExpiry");

                    b.ToTable("jobs", (string)null);
                });

            modelBuilder.Entity("com.lifepixer.mangapixer.Server.Persistence.Entities.LibraryEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CaseComparisonPolicy")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<long>("CatalogRevision")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DefaultReaderMode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastScanCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("MetadataEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MetadataPrecedence")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("MetadataSeriesInfoHidden")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("RootIdentity")
                        .HasColumnType("TEXT");

                    b.Property<string>("RootPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ScanSchedule")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.ToTable("libraries", (string)null);
                });

            modelBuilder.Entity("com.lifepixer.mangapixer.Server.Persistence.Entities.LibraryGrantEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("GrantedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LibraryId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LibraryId");

                    b.HasIndex("UserId", "LibraryId")
                        .IsUnique();

                    b.ToTable("library_grants", (string)null);
                });

            modelBuilder.Entity("com.lifepixer.mangapixer.Server.Persistence.Entities.MetadataRecordEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AltTitlesJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("CategoriesJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatorsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("CrossIdsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtraJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("FetchState")
                        .HasColumnType("INTEGER");

                    b.Property<long>("FetchedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Format")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GenresJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageRemoteUrl")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("ImageState")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ImageVersion")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("LatestChapter")
                        .HasColumnType("REAL");

                    b.Property<bool?>("LicensedEn")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Origin")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OriginStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OriginVolumes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderType")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<long?>("ProviderUpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("PublishersJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("RecordKind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SiteUrl")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceKind")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StartYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StatusText")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("TranslationComplete")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("Webtoon")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("Provider", "ExternalId")
                        .IsUnique();

                    b.ToTable("metadata_records", (string)null);
                });

            modelBuilder.Entity("com.lifepixer.mangapixer.Server.Persistence.Entities.NodeSeriesLinkEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LibraryId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MatchMethod")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("MatchScore")
                        .HasColumnType("REAL");

                    b.Property<long>("NodeId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("RecordId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NodeId")
                        .IsUnique();

                    b.HasIndex("RecordId");

                    b.HasIndex("LibraryId", "State");

                    b.ToTable("node_series_links", (string)null);
                });

            modelBuilder.Entity("com.lifepixer.mangapixer.Server.Persistence.Entities.PageEntryEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnimationState")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ByteSize")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ContentVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EntryKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("Ordinal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PageState")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceEntryLocator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("ItemId", "ContentVersion", "EntryKey")
                        .IsUnique();

                    b.HasIndex("ItemId", "ContentVersion", "Ordinal")
                        .IsUnique();

                    b.ToTable("page_entries", (string)null);
                });

            modelBuilder.Entity("com.lifepixer.mangapixer.Server.Persistence.Entities.PrivateLibraryEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("LibraryId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MarkedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "LibraryId")
                        .IsUnique();

                    b.ToTable("private_libraries", (string)null);
                });

            modelBuilder.Entity("com.lifepixer.mangapixer.Server.Persistence.Entities.ReadMarkEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MarkedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("UserId", "ItemId")
                        .IsUnique();

                    b.ToTable("read_marks", (string)null);
                });

            modelBuilder.Entity("com.lifepixer.mangapixer.Server.Persistence.Entities.ReaderPreferencesEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AlwaysOpenReadFromStart")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DefaultReaderMode")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("FavoritesSearchProminence")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HomeRecentWindowDays")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LibraryCardSize")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LibraryDirection")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LibraryGridDensity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LibraryPageSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LibrarySort")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LibraryViewMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ListColumns")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PreferDoubleSpread")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PreferredBackground")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ReducedMotion")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowFavoritesHomeRow")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("reader_preferences", (string)null);
                });

            modelBuilder.Entity("com.lifepixer.mangapixer.Server.Persistence.Entities.ReadingProgressEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CompletedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ContentVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EntryKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("HiddenFromContinue")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastMutationId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("NormalizedAnchor")
                        .HasColumnType("REAL");

                    b.Property<int>("Ordinal")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Revision")
                        .HasColumnType("INTEGER");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ItemId")
                        .IsUnique();

                    b.HasIndex("UserId", "UpdatedAt");

                    b.ToTable("reading_progress", (string)null);
                });

            modelBuilder.Entity("com.lifepixer.mangapixer.Server.Persistence.Entities.ScanObservationEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("ByteLength")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("FileIdentity")
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LibraryId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ModificationTicks")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ObservationStatus")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ParentNodeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ParentPathKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PathKey")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SanitizedError")
                        .HasColumnType("TEXT");

                    b.Property<long>("ScanRunId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ScanRunId");

                    b.HasIndex("LibraryId", "PathKey");

                    b.ToTable("scan_observations", (string)null);
                });

            modelBuilder.Entity("com.lifepixer.mangapixer.Server.Persistence.Entities.ScanRunEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CompletedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LeaseExpiry")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LeaseOwner")
                        .HasColumnType("TEXT");

                    b.Property<long>("LibraryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NodesAdded")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NodesObserved")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NodesTombstoned")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NodesUpdated")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SanitizedError")
                        .HasColumnType("TEXT");

                    b.Property<long>("ScanRevision")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StartedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LibraryId");

                    b.HasIndex("Status");

                    b.ToTable("scan_runs", (string)null);
                });

            modelBuilder.Entity("com.lifepixer.mangapixer.Server.Persistence.Entities.SessionEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("ExpiresAt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("INTEGER");

                    b.Property<long>("IssuedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("TicketId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("TicketId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("sessions", (string)null);
                });

            modelBuilder.Entity("com.lifepixer.mangapixer.Server.Persistence.Entities.UserEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ActivationTokenConsumed")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ActivationTokenExpiry")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActivationTokenHash")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ForcePasswordChange")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPendingActivation")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastLoginAt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LockoutEnd")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NormalizedUserName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique();

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("com.lifepixer.mangapixer.Server.Persistence.Entities.ArchiveItemEntity", b =>
                {
                    b.HasOne("com.lifepixer.mangapixer.Server.Persistence.Entities.CatalogNodeEntity", "Node")
                        .WithOne("ArchiveItem")
                        .HasForeignKey("com.lifepixer.mangapixer.Server.Persistence.Entities.ArchiveItemEntity", "NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Node");
                });

            modelBuilder.Entity("com.lifepixer.mangapixer.Server.Persistence.Entities.ArchiveSpreadLayoutEntity", b =>
                {
                    b.HasOne("com.lifepixer.mangapixer.Server.Persistence.Entities.CatalogNodeEntity", "Node")
                        .WithMany()
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Node");
                });

            modelBuilder.Entity("com.lifepixer.mangapixer.Server.Persistence.Entities.BookmarkEntity", b =>
                {
                    b.HasOne("com.lifepixer.mangapixer.Server.Persistence.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("com.lifepixer.mangapixer.Server.Persistence.Entities.CatalogNodeEntity", b =>
                {
                    b.HasOne("com.lifepixer.mangapixer.Server.Persistence.Entities.LibraryEntity", "Library")
                        .WithMany("Nodes")
                        .HasForeignKey("LibraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("com.lifepixer.mangapixer.Server.Persistence.Entities.CatalogNodeEntity", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Library");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("com.lifepixer.mangapixer.Server.Persistence.Entities.EmbeddedMetadataEntity", b =>
                {
                    b.HasOne("com.lifepixer.mangapixer.Server.Persistence.Entities.CatalogNodeEntity", "Node")
                        .WithMany()
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Node");
                });

            modelBuilder.Entity("com.lifepixer.mangapixer.Server.Persistence.Entities.FavoriteEntity", b =>
                {
                    b.HasOne("com.lifepixer.mangapixer.Server.Persistence.Entities.CatalogNodeEntity", "Node")
                        .WithMany()
                        .HasForeignKey("CatalogNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("com.lifepixer.mangapixer.Server.Persistence.Entities.UserEntity", "User")
                        .WithMany("Favorites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Node");

                    b.Navigation("User");
                });

            modelBuilder.Entity("com.lifepixer.mangapixer.Server.Persistence.Entities.FolderMetadataPrecedenceEntity", b =>
                {
                    b.HasOne("com.lifepixer.mangapixer.Server.Persistence.Entities.CatalogNodeEntity", "Node")
                        .WithMany()
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Node");
                });

            modelBuilder.Entity("com.lifepixer.mangapixer.Server.Persistence.Entities.FolderReaderDefaultEntity", b =>
                {
                    b.HasOne("com.lifepixer.mangapixer.Server.Persistence.Entities.CatalogNodeEntity", "Node")
                        .WithMany()
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Node");
                });

            modelBuilder.Entity("com.lifepixer.mangapixer.Server.Persistence.Entities.HomeExcludedLibraryEntity", b =>
                {
                    b.HasOne("com.lifepixer.mangapixer.Server.Persistence.Entities.UserEntity", "User")
                        .WithMany("HomeExcludedLibraries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("com.lifepixer.mangapixer.Server.Persistence.Entities.ItemReaderOverridesEntity", b =>
                {
                    b.HasOne("com.lifepixer.mangapixer.Server.Persistence.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("com.lifepixer.mangapixer.Server.Persistence.Entities.LibraryGrantEntity", b =>
                {
                    b.HasOne("com.lifepixer.mangapixer.Server.Persistence.Entities.LibraryEntity", "Library")
                        .WithMany("Grants")
                        .HasForeignKey("LibraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("com.lifepixer.mangapixer.Server.Persistence.Entities.UserEntity", "User")
                        .WithMany("LibraryGrants")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Library");

                    b.Navigation("User");
                });

            modelBuilder.Entity("com.lifepixer.mangapixer.Server.Persistence.Entities.NodeSeriesLinkEntity", b =>
                {
                    b.HasOne("com.lifepixer.mangapixer.Server.Persistence.Entities.LibraryEntity", null)
                        .WithMany()
                        .HasForeignKey("LibraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("com.lifepixer.mangapixer.Server.Persistence.Entities.CatalogNodeEntity", "Node")
                        .WithMany()
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("com.lifepixer.mangapixer.Server.Persistence.Entities.MetadataRecordEntity", "Record")
                        .WithMany()
                        .HasForeignKey("RecordId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Node");

                    b.Navigation("Record");
                });

            modelBuilder.Entity("com.lifepixer.mangapixer.Server.Persistence.Entities.PageEntryEntity", b =>
                {
                    b.HasOne("com.lifepixer.mangapixer.Server.Persistence.Entities.ArchiveItemEntity", "Item")
                        .WithMany("Pages")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("com.lifepixer.mangapixer.Server.Persistence.Entities.PrivateLibraryEntity", b =>
                {
                    b.HasOne("com.lifepixer.mangapixer.Server.Persistence.Entities.UserEntity", "User")
                        .WithMany("PrivateLibraries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("com.lifepixer.mangapixer.Server.Persistence.Entities.ReadMarkEntity", b =>
                {
                    b.HasOne("com.lifepixer.mangapixer.Server.Persistence.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("com.lifepixer.mangapixer.Server.Persistence.Entities.ReaderPreferencesEntity", b =>
                {
                    b.HasOne("com.lifepixer.mangapixer.Server.Persistence.Entities.UserEntity", "User")
                        .WithOne("Preferences")
                        .HasForeignKey("com.lifepixer.mangapixer.Server.Persistence.Entities.ReaderPreferencesEntity", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("com.lifepixer.mangapixer.Server.Persistence.Entities.ReadingProgressEntity", b =>
                {
                    b.HasOne("com.lifepixer.mangapixer.Server.Persistence.Entities.UserEntity", "User")
                        .WithMany("ReadingProgress")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("com.lifepixer.mangapixer.Server.Persistence.Entities.SessionEntity", b =>
                {
                    b.HasOne("com.lifepixer.mangapixer.Server.Persistence.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("com.lifepixer.mangapixer.Server.Persistence.Entities.ArchiveItemEntity", b =>
                {
                    b.Navigation("Pages");
                });

            modelBuilder.Entity("com.lifepixer.mangapixer.Server.Persistence.Entities.CatalogNodeEntity", b =>
                {
                    b.Navigation("ArchiveItem");
                });

            modelBuilder.Entity("com.lifepixer.mangapixer.Server.Persistence.Entities.LibraryEntity", b =>
                {
                    b.Navigation("Grants");

                    b.Navigation("Nodes");
                });

            modelBuilder.Entity("com.lifepixer.mangapixer.Server.Persistence.Entities.UserEntity", b =>
                {
                    b.Navigation("Favorites");

                    b.Navigation("HomeExcludedLibraries");

                    b.Navigation("LibraryGrants");

                    b.Navigation("Preferences");

                    b.Navigation("PrivateLibraries");

                    b.Navigation("ReadingProgress");
                });
#pragma warning restore 612, 618
        }
    }
}
